title: Save the Antioch Theatre
description: The historic Antioch Theatre in downtown Antioch, Illinois has closed after nearly 100 years. Help us open its doors once again!

destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:categories/:title
markdown: rdiscount
pygments: true
